<a href="https://colab.research.google.com/github/amuthalingeswaranbose/Amuthan_NLP_Learnings/blob/main/NLP_Sentence_Transformer(SBERT).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Install

In [1]:
!pip install -U sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 19.2 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=58918e28ae36027a2cfd2b1650ab0e75ceefc2cdc3bfc22913584cad703ec560
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence-transformers


# Import

In [2]:
from sentence_transformers import SentenceTransformer, util

In [3]:
model = SentenceTransformer('all-miniLM-L6-v2')
model

.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

train_script.py:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Normalize()
)

# 1.Embedding

In [4]:
sentences = [
    "This framework generates embedding for each input sentence",
    "Sentence are passed as a list of stings."
 ]

embeddings = model.encode(sentences)


for sentence, embedding in zip(sentences, embeddings):
  print(f"Sentence: {sentence}")
  print(f"Sentence count: {len(sentence)}, Embedding count: {len(embedding)}")
  print(f"Embedding: {embedding}")
  print(" ")

Sentence: This framework generates embedding for each input sentence
Sentence count: 58, Embedding count: 384
Embedding: [-6.91261189e-03 -3.62894423e-02 -2.18610410e-02  1.13818264e-02
  4.25384864e-02  1.24863945e-01  3.01178545e-02 -3.15150470e-02
  3.38303782e-02 -7.66847879e-02  1.20255286e-02 -4.15239148e-02
  4.81980294e-02  1.67389922e-02 -7.33146295e-02  8.39758962e-02
  2.76714936e-03  4.19141129e-02 -4.62020524e-02 -1.12435028e-01
 -2.36533806e-02  6.44106045e-02  4.85518575e-02 -4.90319133e-02
 -4.05254774e-02  4.44705337e-02 -4.74040434e-02  6.91369409e-03
  1.09921932e-01  9.62937344e-03  3.35711241e-02 -3.39445956e-02
  1.79634485e-02  7.73302019e-02  3.85682983e-03  1.92318968e-02
 -1.43055692e-02  2.38440074e-02 -4.99975570e-02 -1.53257493e-02
 -2.34336369e-02 -1.26113901e-02  2.45836359e-02  1.66354310e-02
  8.51942748e-02 -4.40953448e-02 -8.38720500e-02 -1.40060056e-02
 -1.63426939e-02  1.66167375e-02 -8.57066736e-02 -5.24259210e-02
 -1.22594461e-02  2.15967167e-02 -

# 2.Sentence Similarity (Cosing - similarity)

In [5]:
emb1 = model.encode('I am eating Apple')
emb2 = model.encode('I like fruites')

cos_sim = util.cos_sim(emb1, emb2)

print(f'Cosine Similarity: {cos_sim}')

Cosine Similarity: tensor([[0.5304]])


## Compute cosine similarity between paris

In [6]:
sentences = [
    "A man is eating a food.",
    "A man is eating a piece of bread.",
    "The girl is carring a baby.",
    "A man is ridding a horse.",
    "Two men pushed carts through the woods.",
    "A man is riding a horse on a enclosed ground.",
    "A monkey is playing drums.",
    "Someone in a gorilla costume playing a set of drums"
]

embeddings = model.encode(sentences)
print(f"Embedding count: {len(embeddings)}")

cos_siml = util.cos_sim(embeddings, embeddings)

print(f'Cosine Similarity: {cos_siml}')

Embedding count: 8
Cosine Similarity: tensor([[ 1.0000,  0.7628, -0.0566,  0.1996, -0.0391,  0.1877,  0.0474,  0.0538],
        [ 0.7628,  1.0000,  0.0198,  0.1473, -0.0216,  0.1239,  0.0362,  0.0178],
        [-0.0566,  0.0198,  1.0000, -0.0655, -0.1159, -0.0639,  0.0673,  0.0377],
        [ 0.1996,  0.1473, -0.0655,  1.0000,  0.1343,  0.6509,  0.0503,  0.1229],
        [-0.0391, -0.0216, -0.1159,  0.1343,  1.0000,  0.0635, -0.0380, -0.0684],
        [ 0.1877,  0.1239, -0.0639,  0.6509,  0.0635,  1.0000,  0.0539,  0.1582],
        [ 0.0474,  0.0362,  0.0673,  0.0503, -0.0380,  0.0539,  1.0000,  0.6142],
        [ 0.0538,  0.0178,  0.0377,  0.1229, -0.0684,  0.1582,  0.6142,  1.0000]])


## Add all pairs to a list  with their  consine similarity score

In [9]:
all_sentence_similairity = []

for i in range(0, len(cos_siml)-1):
  for j in range(i+1, len(cos_siml)):
    all_sentence_similairity.append((cos_siml[i][j], i, j))


for sent_sim in all_sentence_similairity:
  print(f"sentence_similairity: {sent_sim}")

sentence_similairity: (tensor(0.7628), 0, 1)
sentence_similairity: (tensor(-0.0566), 0, 2)
sentence_similairity: (tensor(0.1996), 0, 3)
sentence_similairity: (tensor(-0.0391), 0, 4)
sentence_similairity: (tensor(0.1877), 0, 5)
sentence_similairity: (tensor(0.0474), 0, 6)
sentence_similairity: (tensor(0.0538), 0, 7)
sentence_similairity: (tensor(0.0198), 1, 2)
sentence_similairity: (tensor(0.1473), 1, 3)
sentence_similairity: (tensor(-0.0216), 1, 4)
sentence_similairity: (tensor(0.1239), 1, 5)
sentence_similairity: (tensor(0.0362), 1, 6)
sentence_similairity: (tensor(0.0178), 1, 7)
sentence_similairity: (tensor(-0.0655), 2, 3)
sentence_similairity: (tensor(-0.1159), 2, 4)
sentence_similairity: (tensor(-0.0639), 2, 5)
sentence_similairity: (tensor(0.0673), 2, 6)
sentence_similairity: (tensor(0.0377), 2, 7)
sentence_similairity: (tensor(0.1343), 3, 4)
sentence_similairity: (tensor(0.6509), 3, 5)
sentence_similairity: (tensor(0.0503), 3, 6)
sentence_similairity: (tensor(0.1229), 3, 7)
sent

## Sort list by the highest  consine similarity score

In [15]:
all_sentence_similairity = sorted(all_sentence_similairity, key=lambda x: x[0], reverse=True)
all_sentence_similairity

for score, i, j in all_sentence_similairity[:5]:
  print("{}\t{}\t{:.4f}".format(sentences[i], sentences[j], cos_siml[i][j]))

A man is eating a food.	A man is eating a piece of bread.	0.7628
A man is ridding a horse.	A man is riding a horse on a enclosed ground.	0.6509
A monkey is playing drums.	Someone in a gorilla costume playing a set of drums	0.6142
A man is eating a food.	A man is ridding a horse.	0.1996
A man is eating a food.	A man is riding a horse on a enclosed ground.	0.1877


# 3.Semantic Search

In [21]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('clips/mfaq')
model

/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py:381: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: XLMRobertaModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
)

In [22]:
question = "<Q>How many models can I host on HuggingFace?"
answer_1 = "<A>All plans come with unlimited private models and datasets."
answer_2 = "<A>AutoNLP is an automatic way to train and deploy state-of-the-art NLP models, seamlessly integrated with the Hugging Face ecosystem."
answer_3 = "<A>Based on how much training data and model variants are created, we send you a compute cost and payment link - as low as $10 per job."


In [24]:
query_embedding = model.encode(question)
print(f"query_embedding: {query_embedding}")
print(f"query_embedding count: {len(query_embedding)}")

query_embedding: [ 3.20170850e-01  2.05861509e-01 -6.34304464e-01 -6.46892548e-01
  4.39985931e-01  3.68800461e-01 -3.66198033e-01  1.30099922e-01
 -1.74854234e-01 -2.14604318e-01  2.07185656e-01 -7.19301343e-01
  3.07514638e-01 -2.05244392e-01 -2.61264704e-02  1.24591827e+00
 -1.68421194e-01 -1.68158948e-01 -3.68270218e-01  2.81881303e-01
  4.20900248e-02  4.80952442e-01  9.40893948e-01  1.10518463e-01
  7.88861454e-01  1.15782225e+00  4.94810253e-01 -2.39746958e-01
 -8.32092762e-03  5.70936799e-01 -1.24109156e-01  1.66229054e-01
  1.73913047e-01  3.55794936e-01  6.39625728e-01  4.24508035e-01
  2.75370419e-01 -1.82988614e-01  3.32177311e-01 -5.16086221e-01
  8.29206884e-01 -2.27028832e-01  5.78885436e-01  3.24211746e-01
  5.38548887e-01 -1.18061170e-01  2.22760782e-01  1.54612940e-02
 -1.13962129e-01 -3.83946925e-01 -3.56751561e-01 -9.12433118e-02
 -5.38550224e-03 -9.18848962e-02 -1.46795854e-01 -9.02788103e-01
  7.91933611e-02  5.32796443e-01  7.40615651e-02 -9.52469289e-01
  4.5809

In [28]:
answer_embedding = model.encode([answer_1, answer_2, answer_3])
print(f"answer_embedding: {answer_embedding}")
print(f"answer_embedding count: {len(answer_embedding)}")

answer_embedding: [[ 0.1601236   0.17007051 -0.1403386  ... -0.41873822 -0.05898611
  -0.1294917 ]
 [-0.31949535 -0.02250298 -0.03597436 ... -0.1024162   0.22197512
   0.27600354]
 [-0.12174771  0.00124673 -0.08740652 ... -0.26924002 -0.07882904
   0.1271995 ]]
answer_embedding count: 3


In [29]:
# Semantic Search

print(util.semantic_search(query_embedding, answer_embedding))

[[{'corpus_id': 0, 'score': 0.5646329522132874}, {'corpus_id': 2, 'score': 0.5142344832420349}, {'corpus_id': 1, 'score': 0.4730042517185211}]]


## QA Mode

In [35]:
from transformers import pipeline

qa_model = pipeline('question-answering')

question = "How many models can I host on HuggingFace?"
context = "All plans come with unlimited private models and datasets."


qa_model(question = question, context = context)

No model was supplied, defaulted to distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


{'score': 0.7017176747322083, 'start': 20, 'end': 29, 'answer': 'unlimited'}

# 4.Clustering

In [37]:
from sklearn.cluster import KMeans
import numpy as np

model = SentenceTransformer('all-MiniLM-L6-V2')
model

.gitattributes:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

data_config.json:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

train_script.py:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

SentenceTransformer(
  (0): Transformer({'max_seq_length': 256, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Normalize()
)

In [38]:
# Embedd and normalize the corpus

# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]

# embedding corupus
corpus_embedding = model.encode(corpus)
corpus_embedding

array([[ 0.03324159,  0.00440611, -0.00627698, ...,  0.06917298,
        -0.02458487, -0.03756437],
       [ 0.05251842,  0.05524131, -0.0111882 , ..., -0.01619394,
        -0.06022897, -0.04115053],
       [-0.00858896,  0.01801807,  0.05754678, ...,  0.06797205,
         0.0076367 , -0.03118757],
       ...,
       [ 0.05438586,  0.05397905, -0.0036798 , ...,  0.03249276,
         0.02187709,  0.06213458],
       [-0.00162545,  0.04804113,  0.0103358 , ..., -0.00226648,
         0.09303317,  0.03106402],
       [ 0.03091299,  0.00874069, -0.06028781, ...,  0.04663473,
         0.03548018, -0.00794349]], dtype=float32)

# Normalize the embedding to units lenght

In [39]:
corpus_embedding = corpus_embedding / np.linalg.norm(corpus_embedding, axis=1, keepdims=True)
corpus_embedding

array([[ 0.03324159,  0.00440611, -0.00627698, ...,  0.06917299,
        -0.02458487, -0.03756437],
       [ 0.05251842,  0.05524131, -0.0111882 , ..., -0.01619394,
        -0.06022898, -0.04115053],
       [-0.00858896,  0.01801807,  0.05754678, ...,  0.06797205,
         0.0076367 , -0.03118757],
       ...,
       [ 0.05438586,  0.05397906, -0.0036798 , ...,  0.03249277,
         0.0218771 ,  0.06213458],
       [-0.00162545,  0.04804112,  0.0103358 , ..., -0.00226648,
         0.09303316,  0.03106401],
       [ 0.03091299,  0.0087407 , -0.06028781, ...,  0.04663474,
         0.03548019, -0.00794349]], dtype=float32)

In [40]:
corpus_embedding[0]

array([ 3.32415923e-02,  4.40611131e-03, -6.27698097e-03,  4.83787395e-02,
       -1.38702288e-01, -3.36174108e-02,  1.01128370e-01, -5.43849692e-02,
       -4.32477817e-02, -3.99411246e-02,  7.78633682e-03, -1.27489287e-02,
       -6.68302402e-02, -1.73865426e-02,  4.74506281e-02, -5.77242412e-02,
        1.01888366e-01, -9.11662937e-04,  8.22615027e-02, -5.03415726e-02,
        6.77302927e-02,  4.08765152e-02, -3.58018912e-02, -1.00682415e-01,
       -6.69354713e-03, -5.31686284e-02,  1.00335158e-01, -5.46135865e-02,
       -2.28481367e-02,  1.38387140e-02,  7.48658478e-02, -6.17880039e-02,
        6.39215931e-02,  1.62387323e-02, -5.32299615e-02, -3.86084318e-02,
        3.15275863e-02, -8.11529905e-02, -3.31432372e-02, -5.38505905e-04,
       -3.96069745e-03, -1.52734164e-02, -9.86421946e-04,  9.57987979e-02,
       -5.42920306e-02,  1.84572097e-02, -1.07143618e-01,  1.38884904e-02,
        3.94072384e-02, -2.69243568e-02, -9.15988758e-02, -1.14195142e-02,
        3.38137113e-02, -

In [53]:
clustering_model = KMeans(n_clusters=4)
clustering_model.fit(corpus_embedding)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[3 3 0 3 3 2 2 0 0 1 1 0 0 0 2]


/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [54]:
clustered_sentences = {}

for sentence_id, cluster_id in enumerate(cluster_assignment):
  if cluster_id not in clustered_sentences:
    clustered_sentences[cluster_id] = []

  clustered_sentences[cluster_id].append(corpus[sentence_id])

print(f"clustered_sentences: {clustered_sentences}")


clustered_sentences: {3: ['A man is eating food.', 'A man is eating a piece of bread.', 'A man is eating pasta.', 'A Woman is eating Biryani.'], 0: ['Horse is eating grass.', 'A man is riding a horse.', 'A man is riding a white horse on an enclosed ground.', 'A cheetah is running behind its prey.', 'A cheetah chases prey on across a field.', 'The cheetah is chasing a man who is riding the horse.'], 2: ['The girl is carrying a baby.', 'The baby is carried by the woman', 'man and women with their baby are watching cheetah in zoo'], 1: ['A monkey is playing drums.', 'Someone in a gorilla costume is playing a set of drums.']}


In [ ]:
""